# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ddev < Formula
  desc "DDEV"
  homepage "https://github.com/drud/ddev"
  version "1.21.5-aa1"
  license "Apache 2"

  depends_on "mkcert"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/drud/ddev/releases/download/v1.21.5-aa1/ddev_macos-arm64.v1.21.5-aa1.tar.gz"
      sha256 "2dad1f1bae185785b4bc3ac1866874850dfbfe72c3229d10f8d4ecc523264c4a"

      def install
        if build.head?
            os = OS.mac? ? "darwin" : "linux"
            arch = Hardware::CPU.arm? ? "arm64" : "amd64"
            system "mkdir", "-p", "#{bin}"
            system "make", "VERSION=v#{version}", "COMMIT=v#{version}"
            system "cp", ".gotmp/bin/" + os + "_" + arch + "/ddev", "#{bin}/ddev"
        else
            bin.install "ddev"
            bash_completion.install "ddev_bash_completion.sh" => "ddev"
            zsh_completion.install "ddev_zsh_completion.sh" => "ddev"
            fish_completion.install "ddev_fish_completion.sh" => "ddev"
        end
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/drud/ddev/releases/download/v1.21.5-aa1/ddev_macos-amd64.v1.21.5-aa1.tar.gz"
      sha256 "c95090e7bb85fa2590906cdcbefcf1797c4d0cb9515f433ed7c55f495a95a61f"

      def install
        if build.head?
            os = OS.mac? ? "darwin" : "linux"
            arch = Hardware::CPU.arm? ? "arm64" : "amd64"
            system "mkdir", "-p", "#{bin}"
            system "make", "VERSION=v#{version}", "COMMIT=v#{version}"
            system "cp", ".gotmp/bin/" + os + "_" + arch + "/ddev", "#{bin}/ddev"
        else
            bin.install "ddev"
            bash_completion.install "ddev_bash_completion.sh" => "ddev"
            zsh_completion.install "ddev_zsh_completion.sh" => "ddev"
            fish_completion.install "ddev_fish_completion.sh" => "ddev"
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/drud/ddev/releases/download/v1.21.5-aa1/ddev_linux-arm64.v1.21.5-aa1.tar.gz"
      sha256 "0f0b3586d755d1a5ae18ec8679f9694ada817a7897c852e8b7c2368e4c9ec1d2"

      def install
        if build.head?
            os = OS.mac? ? "darwin" : "linux"
            arch = Hardware::CPU.arm? ? "arm64" : "amd64"
            system "mkdir", "-p", "#{bin}"
            system "make", "VERSION=v#{version}", "COMMIT=v#{version}"
            system "cp", ".gotmp/bin/" + os + "_" + arch + "/ddev", "#{bin}/ddev"
        else
            bin.install "ddev"
            bash_completion.install "ddev_bash_completion.sh" => "ddev"
            zsh_completion.install "ddev_zsh_completion.sh" => "ddev"
            fish_completion.install "ddev_fish_completion.sh" => "ddev"
        end
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/drud/ddev/releases/download/v1.21.5-aa1/ddev_linux-amd64.v1.21.5-aa1.tar.gz"
      sha256 "7bc22f7c79f131c8ed8f9f5aad85833e60cdd814c3a08e3b5ed90ee0b58ac173"

      def install
        if build.head?
            os = OS.mac? ? "darwin" : "linux"
            arch = Hardware::CPU.arm? ? "arm64" : "amd64"
            system "mkdir", "-p", "#{bin}"
            system "make", "VERSION=v#{version}", "COMMIT=v#{version}"
            system "cp", ".gotmp/bin/" + os + "_" + arch + "/ddev", "#{bin}/ddev"
        else
            bin.install "ddev"
            bash_completion.install "ddev_bash_completion.sh" => "ddev"
            zsh_completion.install "ddev_zsh_completion.sh" => "ddev"
            fish_completion.install "ddev_fish_completion.sh" => "ddev"
        end
      end
    end
  end

  head "https://github.com/drud/ddev.git", branch: "master"
  depends_on "go" => :build
  depends_on "make" => :build

  test do
    system "#{bin}/ddev --version"
  end
end
